---
- hosts: katuma-dev
  remote_user: ubuntu
  sudo: yes
  # TODO: Doc in wiki. A manos entrando a la maquina. No hay mas. Inline script con vagrant
  # pre_tasks:
    # - name: apt-get update 
      # raw: apt-get update -qq 
    # - name: Install python 2.7 
      # raw: apt-get install -qq python2.7  # Missing sudo? doesn't it run with sudo?

  roles:
    - common
    - db_server
    - vendor/DavidWittman.redis

  vars_files:
    - secrets/development.yml
  vars:
    rails_environment: development
    database_name: katuma_development
    database_user: katuma
    development_host: 10.0.3.133
    ansible_python_interpreter: /usr/bin/python2.7
    postgresql_version: '9.5'
    nodejs_version: '4.x'
