---
- name: Install build_essentials package
  apt:
    name: 'build-essential'
    state: present

- name: Install ca-certificates
  apt:
    name: 'ca-certificates'
    state: present

- name: Install Git package
  apt:
    name: 'git'
    state: present

- name: Install curl
  apt:
    name: 'curl'
    state: present

- name: Install wget
  apt:
    name: 'wget'
    state: present
