---
- name: Install build_essentials package
  apt:
    name: 'build-essential'
    state: present

- name: Install ca-certificates
  apt:
    name: 'ca-certificates'
    state: present

- name: Install Git package
  apt:
    name: 'git'
    state: present
